### ISSUE TITLE
Per eye full screen effect

### ISSUE THREAD

**Issue by kariem2k** [googlesamples/cardboard-unity#102]
Hi
I had a simple shader to make effects on each eye camera's render target. It was working fine but I think after upgrading to 0.5.2 things changed. Now the effect appears to be applied on one texture that is imposed on both cameras at once. So for example if I was drawing two circles one circle on each eye (The center of the circle is the center of the eye). Now what happens is one circle is drawn and the center of it between the two eyes. I get the desired effect only when setting DistortionCorrection to None (Both Unity, Native modes don't work) but I need the distortion correction to be active.

Please advice.

Thanks

**Comment by kariem2k** [comment]
I apply the effect by assigning a script component to each eye and that component has OnRenderImage function which calls Blit using the passed source and destination textures.

**Comment by smdol** [comment]
Make sure to turn off Direct Render on the StereoController.

Is this effect added to the cameras in the editor or by script?

**Comment by kariem2k** [comment]
I tried turning it off and it causes lots of rendering artifacts. It is added by script.

**Comment by smdol** [comment]
OK.  The Direct Render option is there because many image effects cause the original problem that you saw: one eye is spread over the whole screen.  But it works by adding a "final" image effect to each eye which ensures that the output goes only to the correct half of the screen.  

Since you are adding your effect by script, it is probably coming after this "final" effect, which causes the artifacts you see when you turn off Direct Render.  

As a test, could you add your effect to the eyes in the editor rather than by script, and turn off Direct Render?  Does this help?

(The method for fixing the problems with image effects changed in 0.5.2, which is why you are setting this happen.  The previous release used a different method, but it was much slower.)

**Comment by kariem2k** [comment]
Thanks you are right. I am now removing the CardboardEye component before applying my effect and then readd it again so it loads after the effect component.
