### ISSUE TITLE
VR-Mode disabled leads to blackscreen on some devices 

### ISSUE THREAD

**Issue by ckrin** [googlesamples/cardboard-unity#121]
Hi,
our game "Sinister Edge" (https://play.google.com/store/apps/details?id=com.everbytestudio.sinisteredge) is live on google playstore for a few weeks. 

The player is able to choose (in main menu) if he wants to play in VR mode. We save this data and set the VR mode accordingly. By default VR mode is disabled on the player prefab, since most players dont use it.
We received a lot of emails from players (vr-mode disabled) adressing the same problem. Some of them use very powerfull devices (for e.g. Tegra 4 tablets). They tell us their screen simply stays black ingame.

i red about problems switching from non vr to vr mode, but this is not the case. 
Does somebody have an idea what could cause this problem? We support large tablets which are definitely not compatible with cardboard, but we set the vr mode boolean to false by default.
Are there any other cardboard actions involved, that could cause the blackscreens? Should we build a second player prefab for non VR players, completely without cardboard?

kind regards from a confused team :)

**Comment by smdol** [comment]
A couple of questions:  This only happens on some tablets?  Is it black screen from launch or only after a certain point in the game?

**Comment by justinwasilenko** [comment]
I have this problem as well, using a Samsung S3 for testing my game. No users have reported it to me yet Been meaning to write about this but haven't been able to documented it with a video

**Comment by ckrin** [comment]
thanks for the fast answers! blackscreen seems to appear from the moment cardboard sdk is involved (main menu is no problem). the blackscreen is not exclusive on tablets. we got mails from s3 users as well. its hard for us to track the problem since most users simply rate 1 star and uninstall the game.

**Comment by smdol** [comment]
I think we have an S3 in the office.  I'll download the game and try it out.

**Comment by HansBernd** [comment]
Experienced this too, if vr mode is enabled by default I can switch it on and off just fine.
If it is disabled by default, my devices (Galaxy Note 2&4) will show a black screen if i try to enable it.

**Comment by justinwasilenko** [comment]
Yep that is exactly the same problem here Hans.
But sometimes, and in the case of this screenshot below VR was enabled on start up and this occurred when I switched VR off.

![screenshot_2015-11-27-11-41-20](https://cloud.githubusercontent.com/assets/11709400/11439471/eca45d3a-94fb-11e5-97f6-ecee44bbbeba.png)

**Comment by justinwasilenko** [comment]
Sadly got a 3 star review from someone that might be related to this bug:

"Zuk Z1. The game looks amazing when in the non vr menus however when turning VR on with the ZukZ1 the whole image turns upsidedown and also zooms in 80% so I can not see anything, I am using a generic vr headset and my own preset for Google cardboard 30mm lens to screen 50mm apart and 50fov for top bottom left and right not sure why it isn't working compatibility issues maybe? I had decided to refund and I just wish it may get updated. WILL CHANGE REVIEW IF IT IS FIXED FOR THE ZUK Z1.."

I think it might be related to this issue however the user also complains of it zooming in? Sorry I can't  ask the person for more info as it's just a review from the Play Store.

* Side note As a developer for Cardboard it's hard to see my once 5 star rating fall because of bugs like this that I can't do much about. I hope by bringing it to your attention it helps you guys get the new update working tip top.

**Comment by smdol** [comment]
Wow, there's a lot of stuff going on in that review.  I'll take it bit by bit...

Does your app allow landscape right orientation?  That will cause the upside-down symptom?  (There may be other causes too.)

The 80% zoom could be due to several factors combining:  1) The change in FOV from mono to whatever profile they had (sounds customized), 2) the phone reporting a wrong DPI.  I don't have one of these phones at hand, so I can't say if that is an issue.  We are trying to resolve the issue of phone DPI inaccuracy in general since we depend on it to compute the screen size, but it is a tough nut to crack.

**Comment by justinwasilenko** [comment]
My app, only allows Landscape Left orientation. So not sure how it would be upside down? Sorry I can't  be more helpful but if you want a .apk of my game I can make it available to you. Or you can find it at http://endspacevr.com

Let me know how I can help :)

**Comment by smdol** [comment]
I can try recreating the user's profile for one thing.  The upside down problem normally happens if you leave on landscape right as an option and they put the phone in the viewer that way too.  (Bug in the SDK.). But there could be other causes.  I've not heard of the user's phone, so I don't know what chipset it has.  Could be an issue there.  If that turns out to be the case, you may want to blacklist that phone till we can figure out what the compatibility issues are (or Unity does).

**Comment by smdol** [comment]
This should be fixed in the new v0.6 release of the SDK.  There was an exception getting thrown which prevented the eye camera's TargetTexture from getting set.

**Comment by ddutchie** [comment]
I'm having this issue in my IOS version of my app. If I disable VR mode to use the Gyro tracking on a 2D camera my scene is Black. I'm not sure when this popped up but it was working prior. 

I found that if I disable the AddCardboardCamera(); when not it vrmode it seems to work. For now...
