### ISSUE TITLE
Remove Cardboard SDK at compilation time depending on preprocessor directives

### ISSUE THREAD

**Issue by ludo6577** [googlesamples/cardboard-unity#133]
Hello,

Is there a way to remove properly the Cardboard SDK at the compilation? Some kind of preprocessor directives that deactivate totally the SDK. Everytime i try i have some exceptions or i still see the Alignment Marker or the Settings Button.

I want to change the camera and use the native Unity system for other devices (gearVR, ...) but i still want to stay compatible with the Cardboard SDK. I think some people will need this very soon as a lot of device will goes out in the next few mouth.

Maybe i take the problem in a wrong way but i don't want to maintain 2 branches with two différents version of my app.

Thank you.

**Comment by smdol** [comment]
Definitely there are bugs related to alignment marker and settings button that we are fixing.  But the SDK does not activate unless the Cardboard.cs script's Awake() function gets called, so the key is to prevent that from occurring.  The tricky part is that any script referring to "Cardboard.SDK" will cause a Cardboard to get instantiated if one is not already awake in the scene (this will change in a future release), so you have to avoid that too.  Probably the sanest way is to instantiate the Cardboard setup at runtime from script, which you can then guard by preprocessor directive or even a simple property check on a "VR Manager" script of some kind.  Rather than using the prefabs, try just adding StereoController to your Main Camera in code, if the app is supposed to be running in Cardboard mode.  (It was set up to be used this way.)

**Comment by ludo6577** [comment]
Thank you very much for your fast answer ! I will give a try a make you a feedback after way.
Hope the next release will come soon, the Cardboard SDK is really a good start for the VR :)

**Comment by ludo6577** [comment]
Thank you! your solution works great! (at least in v0.5.2)
I made a small tutorial for those who want to support the Cardboard SDK and the native Unity Virtual Reality Supported option: https://github.com/ludo6577/VrMultiplatform (change the compilation parameters in one click)

I just downloaded the last version of the Cardboard SDK (0.6) but now when i add the StereoController.cs script to my camera the Cardboard is not activated anymore on phone (but works in the Unity Editor).

**Comment by smdol** [comment]
We're having to do another hotfix, which has held up the doc updates, but in v0.6 we changed Cardboard.SDK to just log an error if it is null, rather than trying to activate automatically.  There were weird bugs happening at shutdown or level load, sometimes even at startup, where two Cardboards would get created instead of one.  The new way to handle this is to call the "Cardboard.Create()" static function just before you add a StereoController to the camera, and it will instantiate for you.  It is OK if Create() is called more than once, only the first time will it do anything.

**Comment by chelder86** [comment]
Thanks for the v0.6! Thanks for the tutorial! :)

**Comment by justinwasilenko** [comment]
Great @ludo6577  thanks for the tutorial / code to make this work. I'm in the process of porting my game to GearVR and this is a huge help.

**Comment by nathanmartz** [comment]
Glad that everything is working!
