### ISSUE TITLE
SDK 0.6 Black border on top

### ISSUE THREAD

**Issue by ITurchenko** [googlesamples/cardboard-unity#141]
After upgrading to new 0.6 version I get black unused space on top screen.
How to reproduce:
1) Start new project
2) Import sdk and demo
3) Open demo scene, select android platform
4) In **Cardboard** script (attached to CardboardMain object) set **Distort Correction** value as **None**
5) Launch

![Example](https://i.gyazo.com/783ccd28b4873dc8a0a2f39b7588cec1.png)

**Comment by smdol** [comment]
This could  happen depending on the phone model and configured viewer that you are using.  Can you reply with that information?

**Comment by ITurchenko** [comment]
Phones: 
Samsung Galaxy S3, android 4.4.4
LG Nexus 5, android 6.0.1

Also problem existing in play mode in Unity 5.3.1

I'm use default settings of demo scene, except of distortion correction
![demo](https://i.gyazo.com/d058cc1bed55592f621344458a8494bf.png)

**Comment by smdol** [comment]
On my Nexus5x using v0.6, I get this:

![screenshot_20160115-173853](https://cloud.githubusercontent.com/assets/10277940/12369845/ed6cb24c-bbb3-11e5-8a9d-0083ab1d9526.png)

Do you get the black space on your phone or just in the editor?  

The editor makes sense because it is rendering for a given phone aspect ratio into the game window which might not be that shape.  Currently, the image hugs the bottom edge of the game window, leaving extra space on top.

On your phone, you will sometimes see extra black around the edges of the images if you are using a Cardboard v1 (the original kind), because the eye viewports do not fill the screen.  But even there, the black is on all 4 sides.

**Comment by ITurchenko** [comment]
After tests, I can say that problem appearing only if scene was started in portrait orientation.
Unfortunately, in our projects VR scene loaded after portrait-oriented start scene.

**Comment by smdol** [comment]
Currently the SDK only properly supports Landscape Left orientation.  This is an issue being worked on, but for now it is necessary for Unity to think the orientation is Landscape Left at the time that you instantiate the Cardboard component.  You can do this in code by assigning to Screen.orientation.

**Comment by ITurchenko** [comment]
Thanks. This workaround solution works fine.

**Comment by ddutchie** [comment]
I had this working perfectly. Set Screen Orientation to LandscapeLeft then enable cardboard component. New Issues have arisen in 0.8. Any tips?
