### ISSUE TITLE
v0.6 Camera view not centered in iOS

### ISSUE THREAD

**Issue by SisadaR** [googlesamples/cardboard-unity#166]
<a href="http://tinypic.com?ref=2iu2tf6" target="_blank"><img src="http://i66.tinypic.com/2iu2tf6.png" border="0" alt="Image and video hosting by TinyPic"></a>

Unity 5.3.2. tested on clean project using sdk v.06 Work fine in editor and android , but on ipod touch gen 5 ios 9.2 it displayed as screen shot.

issue not occurred in sdk v0.52

**Comment by ybeaulieu** [comment]
Have you scanned your viewer's Profile QR code? I noticed having the incorrect profile leads to somewhat intense rendering issues than previous Cardboard versions. That might be the cause of your problem

**Comment by smdol** [comment]
Can you post a screenshot from the 0.5.2 SDK for comparison?  Just from looking at this screenshot, it seems reasonable because of how small the ipod's screen is.  Our QA team tried this and viewed it in a Cardboard, and it looked OK.  

Also, what Cardboard viewer are you using?

**Comment by SisadaR** [comment]
here the pic. both using unity 5.3.2f clean project for v0.52 and v0.6 same cardboard viewer profile(google cardboard v1)

in 0.6 pointers are more closer to the edge and result in images are a little overlap when looking via cardboard lens (work fine in v0.52). Tested on another viewer with adjustable lens v0.6 still not look properly.

<a href="http://tinypic.com?ref=2vklpvl" target="_blank"><img src="http://i63.tinypic.com/2vklpvl.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by mark-steadman** [comment]
I am also having this issue. I would have thought that reducing the stereo multiplier on the StereoController would reduce it, but this seems to have no effect on the position of the gaze pointer.

**Comment by smdol** [comment]
The v0.6 pic looks very much like a V2 Cardboard profile.  (See how the warping is stronger and the eye images touch the center line.  V1 did not do that due to different lenses.)  If you have a V1 Cardboard, you need to set it up by scanning the QR code, and if that doesn't fix it, then the bug is that we're not picking up V1 QR codes properly (the originals had a different format URL than later V2 cardboard), which would be the actual bug here.  You can also test this in the editor by selecting CardboardMain and setting the simulation parameters for the Game window when you hit Play.

**Comment by smdol** [comment]
I should mention:  on iOS the QR code setting is not shared across all apps like it is on Android.  Try scanning the code with this very app.

**Comment by SisadaR** [comment]
the issue didn't occurred in 0.7.2

its been sometimes but I'm pretty sure that I have tired re-scan the QR multiple times

**Comment by nathanmartz** [comment]
Sounds like this is working as intended in the latest version.
