### ISSUE TITLE
iOS build distorted / double vision 

### ISSUE THREAD

**Issue by rrfranco92** [googlesamples/cardboard-unity#188]
Hey,

I'm doing a small app to travel inside a 3d scene but the camera correction doesn't look very good. When I use the app it looks distorted and causing double vision. I think it is affecting the right camera. 

Any idea what could be causing this?

**Comment by smdol** [comment]
Could you add some details about your hardware (phone, Cardboard viewer)?  One problem that shows up on some phones is that they report an inaccurate dots per inch, which throws off the calculation of screen size, and you get double vision.  There are other reasons this could be happening too, but we can start there.

**Comment by rrfranco92** [comment]
Iphone 6 running iOS 9.0.2

The cardboard viewer is this one http://shop.zaak.io/products/google-cardboard-kit

These are the setting I'm using in the cardboard script http://s10.postimg.org/hyjkvbbh5/Captura_de_ecr_2016_03_07_s_21_31_45.png

**Comment by smdol** [comment]
That looks like a V1 Cardboard.  Scanning the QR code worked OK, right?

**Comment by rrfranco92** [comment]
Didn’t try it. I was just running the app straight. Will make it scan the qr so.


A 7 de março de 2016 no 22:34:25, smdol (notifications@github.com) escreveu:

That looks like a V1 Cardboard. Scanning the QR code worked OK, right?

**Comment by rrfranco92** [comment]
Confirmed working.

Thanks for the help!

**Comment by nosmirck** [comment]
@smdol I'm writing here because I don;t want to open a new discussion. I wanted to ask how can I set the default viewer for the app by code so it compiles with that default cardboard viewer. I have the first cardboard viewer released and it doesn't have a QR Code. On android it looks great, but on iOS I get the same problem described here. So, I looked on Google for various QR codes for cardboard until I found one that fits perfecty: "The Classic" [https://cdn.shopify.com/s/files/1/0818/4781/files/qr_viewer_profile_UC_Classic_large.png](This one) 

Can I set the default viewer to this device by code? How can I do that?

**Comment by smdol** [comment]
There's a variable in Cardboard.cs called DefaultDeviceProfile.  You normally just set it the expanded URI that the QR code refers to.  (It only has an effect if you have not manually scanned a QR code.)  For an original model cardboard, try setting it to "http://g.co/cardboard".

**Comment by nosmirck** [comment]
@smdol Great! Thank you!
