### ISSUE TITLE
No UI on Android due to Cardboard.SDK.NativeUILayerSupported?

### ISSUE THREAD

**Issue by andr3wmac** [googlesamples/cardboard-unity#200]
We only use the divider marker from the SDK UI options, and we were using SDK 0.6. Sometime over the past month or so, possibly due to us upgrading unity, the divider line disappeared. It works fine on desktop and iOS but not on android. I just traced it and its due to NativeUILayerSupported being true. I've removed the check and my divider line is back but I'm wondering why does it not draw the UI when NativeUILayerSupported is true and why is NativeUILayerSupported only true for Android?

Should mention we upgraded to 0.7 SDK and no change.

**Comment by smdol** [comment]
Setting NativeUILayerSupported to false causes the divider line to be drawn in Unity using GL calls.  It's chief function is for debugging, and also it draws the line when you play in the Unity editor.

If you start a fresh project with the latest SDK, do you get the native UI divider line?  If so, then the issue might be due to the upgrading.  My suggestion to fix that would be to (per the website's upgrade instructions) delete the Cardboard and Plugins directories, and then import the latest SDK.  

Suggestion: make sure you have a backup, or a clean checkin to source control first.  Also, don't have a Cardboard scene open in the editor when you do this.

**Comment by andr3wmac** [comment]
Just took another look at this and found the problem, it was a stupid mistake on my end. We place the cardboard SDK within a subfolder, and I guess unity wasn't picking up the AndroidManifest.xml file and this was breaking the native UI layer. It's all resolved now :+1:
