### ISSUE TITLE
Error on run with 0.4.9

### ISSUE THREAD

**Issue by justinwasilenko** [googlesamples/cardboard-unity#25]
Just updated my project to 0.4.9 and now getting this error when running my project:

Tiled GPU perf. warning: RenderTexture color surface  (0x0) was not cleared/discarded, doing <run with profiler for info>
UnityEngine.Graphics:Blit(Texture, RenderTexture)
RadialUndistortionEffect:OnRenderImage(RenderTexture, RenderTexture) (at Assets/Cardboard/Scripts/RadialUndistortionEffect.cs:58)
UnityEngine.Camera:Render()
CardboardEye:Render() (at Assets/Cardboard/Scripts/CardboardEye.cs:200)
StereoController:OnPreCull() (at Assets/Cardboard/Scripts/StereoController.cs:281)

**Comment by smdol** [comment]
I've seen that appear as well. It shows up often when using Image Effects
and building for Android. There are lots of forum questions about this,
also asking what to do about it.

None of the suggestions have worked when the texture number is 0x0, because
that's the main screen, and thus the destination RenderTexture reference is
null in OnRenderImage().

Note the the Image Effect is only used in the editor, not on the phone --
it's a preview. So the performance warning does not really apply.

You can turn off the message by telling Unity to not emulate OpenGL ES2 in
Play mode, which is under Edit -> Graphics Emulation. Or you can turn off
the preview by editing the Cardboard component's Simulate Distortion
Correction setting. And you can make Unity not fill the Console window with
these messages by clicking the button that makes it not show repeats.

**Comment by smdol** [comment]
Latest release of Unity (4.6.4, and 5.0.1) seem to fix this issue.
