### ISSUE TITLE
ANR after about 2.5 minutes

### ISSUE THREAD

**Issue by josh-e** [googlesamples/cardboard-unity#27]
Making a unity app with the cardboard sdk  produces and ANR after approximately 2.5 minutes. 

Even if the unity project is just an empty scene, as long as the cardboard plugin (unitycardboardactivity.jar) is included in the project it will produce the error after 2-3 minutes. (works fine until then). I have tested with both 0.4.9 and 0.4.5

Happens on my Verizon HTC M8 (android 5.0.1).

Seems to work fine on Galaxy S5 without producing error.

error: "Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events"

**Comment by smdol** [comment]
Which version of Unity did you build with?

**Comment by josh-e** [comment]
5.0.1f1

**Comment by smdol** [comment]
Confirmed.  Just got it to happen.  Digging into the logcat...

**Comment by smdol** [comment]
Found the CPU usage message a bit further along:

E/ActivityManager(  891): ANR in com.google.vr.anrtest (com.google.vr.anrtest/com.google.vrtoolkit.cardboard.plugins.unity.UnityCardboardActivity), time=734614620
E/ActivityManager(  891): PID: 24417
E/ActivityManager(  891): Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 47.  Wait queue head age: 15506.3ms.)
E/ActivityManager(  891): Load: 13.62 / 51.3 / 93.85
E/ActivityManager(  891): CPU usage from 10495ms to 63ms ago:
E/ActivityManager(  891):   110% 24417/com.google.vr.anrtest: 95% user + 14% kernel / faults: 50866 minor
E/ActivityManager(  891):   14% 456/mediaserver: 14% user + 0% kernel
E/ActivityManager(  891):   7.9% 366/surfaceflinger: 3.7% user + 4.2% kernel

That's quite a CPU load there.

**Comment by josh-e** [comment]
That is exactly what I am seeing

**Comment by smdol** [comment]
What Android version is on your Galaxy S5?

I found a similar looking bug report for Chrome on Lollipop here:
https://code.google.com/p/chromium/issues/detail?id=445138

**Comment by josh-e** [comment]
The s5 is running android 5.0 (also Verizon version)

**Comment by josh-e** [comment]
Is the source for the custom activity publicly available so I could debug a little further myself?

**Comment by smdol** [comment]
Source has not been officially published, but the jars are not obfuscated.

**Comment by nathanmartz** [comment]
Closing old issues.
