### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#38]
I noticed a 25% drop in performance since 0.5 against 0.4.10.
I noticed native distortion correction is forced off for unity 5 builds but disabling correction does not restore FPS.
Do you notice the same?
Any suggestion?

Cheers.
MiCk.

**Comment by smdol** [comment]
The scenes we have profiled showed no performance drop in Unity 4 (for some, there is a performance boost).  I haven't profiled Unity 5 as much, because of that horrible glitchy rendering bug that strikes randomly.  So it is possible that Unity 5 performance has suffered.  If so, I'd guess it has to do with the new shaders and GI, but I'm not sure.  When you turn off distortion correction, did you do it with the Cardboard.SDK.DistortionCorrection flag, or some other way?

**Comment by MiCkSoftware** [comment]
Hi!
As usual tks for the quick reply.
I turn off correction the usual way:

public static void CardboardDistCorrection(bool b) {
		Cardboard.SDK.nativeDistortionCorrection = b;
}

and I use a gateway class for any third party APIs so the probably of doing it in a different manner somewhere else is low.

I am reverting back to 0.4.10 right now in order to confirm the issue. I will let you know.
Cheers.
MiCk.

**Comment by MiCkSoftware** [comment]
And the result: back from 27FPS to 49FPS...
I will import back 0.5.0 from right from github (just in case...) and try to find out more.

**Comment by MiCkSoftware** [comment]
Et voilà!
My gut feelings was right this time. Changing the here below line in AndroidVRDEvice.cs restored performance:
#if UNITY_5
    //debugDisableNativeDistortion = true; // Previsous value
    debugDisableNativeDistortion = false; // Restores performance
#endif

Now it would be great if you could explain why you choose to disabled native code in unity 5 build. That would help me decide what to do (stick to 0.4 or upgrade to 0.5). Did you noticed incompatibility with some (a lot of) phones ? (no issue on my N4 nor N5).

Your help is appreciated.
Thanks.
MiCk.
PS: time after time I began to master the glitch issue. In my case, it's always been a write to SomeObject.getComponent<Renderer>.enabled. Most of the time on 3D Text.

**Comment by smdol** [comment]
The native distortion was turned off in Unity 5 due to that render glitch problem that appears in some scenes but not others (all black screen, all white, or flashing textures).

Good news:  So far it looks like the glitch problem is solved in Unity 5.1 (currently in beta).  None of my tests so far have shown the glitch, even ones that do when I build with 5.0.2.

This means that we'll likely change the debugDisableNativeDistortion flag to false, just like you did here, in the next release.

**Comment by MiCkSoftware** [comment]
OK great. I know what to do now. I'll turn it to false by myself until 0.5.1 and upgrade to unity 5.1 as soon as it is out of beta.
I close this issue. Thanks for your help.
