### ISSUE TITLE
UI elements disappear in VR mode on Android

### ISSUE THREAD

**Issue by yoanngueny** [googlesamples/cardboard-unity#55]
Cardboard 0.5.1 / Unity 5.1.1f1 / Galaxy Note 3 with Android 5.0

In VR mode when adding a canvas (screen overlay), all UI elements are hidden.
No problem in normal mode.
The problem doesn't occur on IOS.

**Comment by smdol** [comment]
I'm a bit surprised it works in iOS, actually.  Normally screen overlays are hidden, because the Cardboard SDK overwrites the framebuffer during distortion correction.  This is why it is recommended to use World Space UI (or rather, one reason why).

**Comment by yoanngueny** [comment]
It's an Iphone 6 IOS 8.1

I'm not a Unity Expert, but I nearly understand the framebuffer problem.
However is there any solution to display a canvas in overlay mode ?
Or can it be fixed in a future version.
Because I think that in some cases according to the user experiences it can be better than the 3D UI.

**Comment by lesmo** [comment]
I don't think so, because overlays won't get distortion correction. World
Space UI get this distortion and look better IMO.

What I've done to make the UI appear to be "static", almost like a regular
overlay, is making the Canvas in World Space be a child of the Head prefab
and position it in a way that is clearly visible by the stereo camera.
That's how I show messages or status updates. Overlays aren't suitable for
Gaze Input.

**Comment by felixwcf** [comment]
I have his problem as well. I'm displaying a custom activity indicator and also white canvas in Overlay mode so when the layout is done loading from asset bundle, the white canvas will have fade out effect and loading indicator will bedisappeared. Now the screen goes totally black.

**Comment by nathanmartz** [comment]
This should be resolved if you use the Unity native distortion correction that came out in 0.5.2.
