### ISSUE TITLE
Volume Buttons blocked?

### ISSUE THREAD

**Issue by JustMeDaFaq** [googlesamples/cardboard-unity#56]
Hi,
just downloaded the unity SDK. Works great so far. Tho, when using the cardboard sdk plugin, the phones volumes buttons are actually not usable anymore, anyone knows how to fix it? (Im using Unity 5.1.2)

**Comment by JustMeDaFaq** [comment]
Found the "issue"

**Comment by microwolnovka** [comment]
How did you solve it?

**Comment by JustMeDaFaq** [comment]
I didnt solved it, it wasnt a bug. Google want the volume buttons to be blocked. I just switched to another SDK, to "solve" it :)

**Comment by smdol** [comment]
Yeah, the volume keys get turned off because when the phone is encased in Cardboard, just holding the outside a little tight can push activate them by accident.  How bad it is depends on which viewer and which model.

But if you touch the gear button, then the volume keys become active again till you press Cancel and go back to the game.
