### ISSUE TITLE
Movement is backwords in 0.5.1

### ISSUE THREAD

**Issue by DavidSotir** [googlesamples/cardboard-unity#62]
I am using Unity 5.1.1 with cardboard sdk version 0.5.1 and the camera movement is completely reversed. I need iOS support so i have to use version 5 of cardboard. I have "Distortion Correction" disabled as i saw that might be a solution to it. No luck.

**Comment by steveulrich** [comment]
What device/android version? Or just in the Unity Editor?

**Comment by DavidSotir** [comment]
Multiple Android devices. Not sure specs at the moment but I believe at least one S5 and iPhone 6+.

**Comment by DavidSotir** [comment]
Fixed the issue! I had my game in Landscape Right. Needed to be in Landscape Left and its fixed. I highly recommend putting a debug error in that insures that it is in the right landscape mode. I actually had to flip my device to remove the google cardboard loading screen, then it played my scene when i flipped back.

**Comment by franklinlyons** [comment]
Glad you found a fix David. I suggest that there not be a landscape requirement. Unity allows the orientation to automatically switch. We've found that certain phones fit better in one orientation vs. the other depending on volume buttons etc. Our research shows that Landscape (home button) Left orientation is the better of the two.

**Comment by lesmo** [comment]
I still vote for a compile time warning...

**Comment by smdol** [comment]
I think the "Place your phone into Cardboard" screen responds only to Landscape Left, but the rest of the Cardboard SDK should work in either landscape mode.  (Note: I'm using the Android convention.  "Left" means the top of the phone goes on the left side.)  The bias towards Landscape Left comes from the original Cardboard model, with the magnet and NFC tag:  The phone needs to be placed so that the sensors can pick up those inputs.  Other viewing devices that don't have either of those inputs can theoretically work with the phone in either orientation.

Question for @DavidSotir: When you were seeing the reversed directions, where was the settings gear icon being drawn (top or bottom)?

**Comment by DavidSotir** [comment]
There was no settings gear. I think I had it turned off though

**Comment by DavidSotir** [comment]
I agree. I think there should be a compile warning or error to tell you. It took me way too long to figure out such a small thing an no where is it documented that this is the fix

**Comment by nathanmartz** [comment]
We'd like to remove the landscape requirement in a future release. Closing as the original issue here was resolved.
