### ISSUE TITLE
Anti-aliasing doesn't work with distortion enabled

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#64]
I am using Unity 5.1 + Unity Cardboard SDK 0.5.1

When lens distortion is enabled, AA doesn't work. Reportedly when distortion is disabled, AA should be working, but I don't think distortion should be disabled. It seems that the motion sickness onset happens quicker without lens distortion.

Please fix AA to work with distortion being on.

**Comment by smdol** [comment]
Turning AA on in Unity's render settings won't have an effect, since the SDK renders to a RenderTexture and then uses native GL code to draw that to the screen.  It should be possible to set up the RenderTexture for AA by overriding or modifying the RenderTexture that the Cardboard.cs script uses.

One app I know of, the Cardboard Design Lab, was able to use 2x MSAA at 60fps by using a different distortion correction technique (moving vertexes in camera space, and rendering direct to the screen).  It's a method that is being looked at for inclusion in the SDK.  The downside is you need will to keep your triangles small onscreen, which will affect how you model them.

(As phones get more powerful in the next few years, this issue may fade away.)

**Comment by motorsep** [comment]
I followed advise of "serg hov" from this thread http://stackoverflow.com/questions/29633049/google-cardboard-for-unity-disables-aa-on-android-device , however that didn't do anything at all.

Could you please provide modified script for Unity to have AA working with lens distortion correction ?

**Comment by smdol** [comment]
Yeah, that advice is for when you aren't using distortion correction.  I believe you have to set the "antiAliasing" field of the RenderTexture to 2 or higher.

http://docs.unity3d.com/ScriptReference/RenderTexture-antiAliasing.html

(I'm suggesting this so you can at least try it without waiting for a new release, which could be whenever.)

**Comment by motorsep** [comment]
I looked into the code and it's kinda over my head :/ (I am an artist)

**Comment by smdol** [comment]
Edit the file BaseVRDevice.cs in Assets/Cardboard/Scripts/VRDevices, and change the function "CreateStereoScreen" to this:

  public virtual RenderTexture CreateStereoScreen() {
    Debug.Log("Creating new default cardboard screen texture.");
    var rt = new RenderTexture(Screen.width, Screen.height, 16, RenderTextureFormat.RGB565);
    rt.antiAliasing = 2;   // <-- This is the new line
    return rt;
  }

You can experiment with 2, 4, and 8.  On my Nexus 5, 2 seems ok performance-wise.

**Comment by motorsep** [comment]
Hmm, doesn't seem to work :(

Forward rendering: http://i.imgur.com/QLwu6aV.png
Deferred: http://i.imgur.com/eYaZ9yX.png

Could it be my hardware? I even enabled Force 4x MSAA in developer's options, and it still looks jagged :/

**Comment by smdol** [comment]
Could be HW.  What phone are you using?

I tried it before posting the suggestion, and it certainly made a difference, at least on the cube (less so on the floor texture).  Also in the frame rate.

Forcing MSAA should have no effect unless you turn off distortion, since the distortion renderer bypasses Unity's main framebuffer.

**Comment by motorsep** [comment]
I am using Galaxy S3 (USA T-Mobile).

**Comment by smdol** [comment]
What version of Android?  The link below says it needs to be 4.2 or higher:

http://www.jayceooi.com/how-to-enable-4x-msaa-in-opengl-es-2-0-android-apps-games/

**Comment by motorsep** [comment]
Android 4.3

Yep, that's what I also do - no effect at all, in any of the games. So must be the hardware issue.

**Comment by MiCkSoftware** [comment]
BTW, anisotropic filtering is on by default for RenderTexture. 
@smdol, Is it intentional to leave it as such? 
@motorsep you may try to disable it (rt.filterMode = FilterMode.Point;)

**Comment by motorsep** [comment]
@MiCkSoftware I think I have "Force AF" option ticked on in the Unity SDK's setting (or somewhere in Unity :) ). Does it interfere with AA ?

**Comment by MiCkSoftware** [comment]
@smdol, may I suggest create texture as below:
RenderTexture rt = new RenderTexture(Screen.width, Screen.height, 16, RenderTextureFormat.RGB565, **RenderTextureReadWrite.Linear**);

**Comment by MiCkSoftware** [comment]
@motorsep I do not know such an option... Are you refering to quality settings? (Edit>Project Settings>Quality).
Also be careful of what quality profile is active when running your app on your phone. 
On my side default AA (from quality) seem to work even with native correction on. I have 2x check.

**Comment by MiCkSoftware** [comment]
@motorsep rendering is fine for me with:
 - Native distortion correction ON.
 - AA 4x from quality settings.
 - rt.antiAliasing =0; rt.filterMode = FilterMode.Point;

**Comment by smdol** [comment]
@MiCkSoftware  Looks like aniso can be set to 0, so I'll do that.  

I also tried linear filtering and didn't see a difference.  But the native distortion correction code sets up a sampler for the texture with filtering hardcoded to linear, so that may be why.  It might help with the Unity fallback distortion correction though.

**Comment by smdol** [comment]
The new v0.5.2 release sets the RenderTexture's antialiasing from the project's Quality settings now.
