### ISSUE TITLE
Cardboard VR for Unity and development road map

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#66]
This isn't an issue per se, but I am wondering if Google treats Cardboard VR as a gimmick and trying to amass user base with affordable VR. 

I can't find a publicly available roadmap for "hardware" and SDK, and judging by the response I got in one of my previous issue report, there is no set schedule for releases. That could mean Google doesn't really care for Cardboard VR at this time, until there is something developed for Magic Leap.

What's the end-game for Cardboard VR ? I don't really want to invest into a dead-end tech :( (I have a feeling Cardboard VR as it exists now will die off to yield the way to Magic Leap and GearVR, as far as mobile VR / AR goes).

Thanks beforehand.

**Comment by smdol** [comment]
Re: Schedule of Releases.  The reason I have to be vague about release dates and upcoming features is that, even though I work full time on Cardboard VR, I am just an engineer and I don't have the authority to publicly commit Google the Corporation to anything.  I'm not in a position to make promises or implications about Google's future plans for Cardboard.

So what I do on this forum is 1) Find out about problems that users run into and new features they would like in the SDK, which I funnel back to the internal issue tracking system;  2) Help users make progress (work around bugs, implement a feature) with the currently released SDK.

Personally I think (and I stress, this is my personal opinion):  Cardboard is a way to turn any capable smartphone into a VR device.  It needs no additional expensive hardware, or any specific phone running a modified version of Android, just something you already likely have in your pocket.  So it can be used pretty much anywhere, at any time, as long as you have a cheap phone-holder with lenses and a QR code.

As long as the size of the audience willing to play with and use VR software (games and apps) is larger than the size of the audience willing to buy additional VR-specific hardware like Leap or Gear, then there's a market for Cardboard or something just like it.  There's also a severe shortage of VR-savvy developers in the world, and Cardboard is a nearly zero-cost way to get in and learn how to do it (assuming you already have the phone).

So that's what I feel about Cardboard, and why I'm glad to be able to work on it.  Again, that's my personal opinion, and I don't (can't) speak for Google Inc in any way.

**Comment by MiCkSoftware** [comment]
+1 and thanks for the help provided here.

**Comment by pansapiens** [comment]
Somewhat reiterating what @smdol has said, but keep in mind that the hard part at the moment is figuring out what works to make a good VR game or app, and making the right tradeoffs between visual quality and performance. The underlying technology is important, but only one part of the equation. Cardboard is a excellent way to get started and discover what works - if it did fade into obscurity, a Unity-based Cardboard app can be relatively easily ported to other high end VR systems. Alternatively, if it grows in popularity and remains supported, you'll be right where the biggest market is.

**Comment by omgwtfgames** [comment]
Somewhat reiterating what @smdol has said, but keep in mind that the hard part at the moment is figuring out what works to make a good VR game or app, and making the right tradeoffs between visual quality and performance. The underlying technology is important, but only one part of the equation. Cardboard is a excellent way to get started and discover what works - if it did fade into obscurity, a Unity-based Cardboard app can be relatively easily ported to other high end VR systems. Alternatively, if it grows in popularity and remains supported, you'll be right where the biggest market is.

_(apologies if you see a double post !)_

**Comment by motorsep** [comment]
I see you points...
